## 部署
- name: Magento
  hosts: all
  become: yes
  become_method: sudo 
  vars_files:
    - vars/main.yml 
  vars_prompt:
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n"
      private: no
      default: 1

    - name: 'data_installation'
      prompt: "\nDo you want to install sample data with magento? [ 1/2 ] \n\n
      1: yes,install it)\n
      2: no)\n"
      private: no
      default: 1

  vars:
    webs_select:
      '1': 'apache'
      '2': 'nginx'
    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'
    data_installation:
      '1': True
      'y': True
      '2': False
      'n': False

    runtime_name: "{{infrastructure_select[webs_selection] | lower}}" 
    magento_webs: "{{webs_select[webs_selection]}}" 
    w9panel_webs: "{{webs_select[webs_selection]}}" 
    sample_data_installation: "{{data_installation[data_installation]}}"

    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 
    w9panel_set_apps: 
      - Magento
  
  pre_tasks:
    - include_vars: roles/role_cloud/vars/cloud_download_url.yml
      when: region == '1' or region == 1

    - debug:
        msg: Magento will be installed on {{w9panel_set_infrastructure}}, OS is {{ansible_distribution}}, region code is {{region}}

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, tags: "role_apache", when: magento_webs == 'apache'}
    - {role: role_nginx, tags: "role_nginx", when: magento_webs == 'nginx'}
    - {role: role_jdk, tags: "role_jdk" }
    - {role: role_elasticsearch , tags: "role_elasticsearch" }
    - {role: role_varnish , tags: "role_varnish" } 
    - {role: role_rabbitmq , tags: "role_rabbitmq"}    
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_redis, tags: "role_redis"}
    - {role: role_docker, tags: "role_docker"}
    - {role: role_php, tags: "role_php"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: magento, tags: "magento"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_init, tags: "role_init"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
