---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    magento_vhost_dir: "{{php_runtime_meta[ansible_os_family][magento_webs].vhost_dir}}"
    magento_vhost_src: "{{php_runtime_meta[ansible_os_family][magento_webs].vhost_src}}"
    magento_service: "{{php_runtime_meta[ansible_os_family][magento_webs].service}}"
    magento_owner: "{{php_runtime_meta[ansible_os_family][magento_webs].owner}}"
    magento_db_password: "{{mysql_root_password}}"

- debug:
    msg: runtime {{ magento_vhost_dir }}, {{magento_vhost_src}}, {{magento_service}}, {{magento_owner}}, {{magento_webs}}, {{ansible_distribution}}

# Magento
- name: Create Magento User
  user:
    name: magento
    shell: /bin/bash
    
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{magento_name}}*

- name: mkdir app folder
  file: 
    path: /data/wwwroot/{{magento_name}}
    state: directory
    mode: 0755

- name: Upload composer authentication keys
  copy:
    src: .config
    dest: /home/magento

- name: Setfacl for Magento own /usr/bin/composer
  shell: |
    setfacl -m u:magento:rx /usr/bin/composer
    setfacl -m u:magento:rw -R /data/wwwroot/magento

- name: Install Magento by composer as the magento (must sudo composer) user, if you use root, system will appear interaction
  shell: sudo composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /data/wwwroot/magento
  become: yes
  become_user: magento

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{magento_name}}" ]; then mv *{{magento_name}}* {{magento_name}}; fi

- name: Delete composer authentication keys
  file:
    path: /home/magento/.config/composer/auth.json
    state: absent

- name: Add cron job for magento
  cron:
    name: magento
    user: "{{magento_owner}}"
    job: "{{item}}"
  with_items:
    - "/usr/bin/php /data/wwwroot/magento/bin/magento cron:run | grep -v 'Ran jobs by schedule' >> /data/wwwroot/magento/var/log/magento.cron.log" 
    - "/usr/bin/php /data/wwwroot/magento/update/cron.php >> /data/wwwroot/magento/var/log/update.cron.log"
    - "/usr/bin/php /data/wwwroot/magento/bin/magento setup:cron:run >> /data/wwwroot/magento/var/log/setup.cron.log"

- name: Upload .htaccess
  copy:
    src: .htaccess
    dest: /data/wwwroot/magento/

- name: Remove default language dir
  file:
    path: /data/wwwroot/magento/vendor/magento/language-zh_hans_cn/
    state: absent

- name: Download language package
  unarchive:
    src: "{{ magento_package_cn }}"
    dest: /data/wwwroot/magento/vendor/magento/
    remote_src: yes

# 系统通用
- name: Permission directory
  shell: |
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{magento_owner}}:{{magento_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{magento_vhost_src}} dest={{magento_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{magento_service}} state=restarted enabled=yes

  - name: restart php-fpm
    service: name=php-fpm state=restarted
