---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    magento_vhost_dir: "{{php_runtime_meta[ansible_distribution][magento_webs].vhost_dir}}"
    magento_vhost_src: "{{php_runtime_meta[ansible_distribution][magento_webs].vhost_src}}"
    magento_service: "{{php_runtime_meta[ansible_distribution][magento_webs].service}}"
    magento_owner: "{{php_runtime_meta[ansible_distribution][magento_webs].owner}}"

- debug:
    msg: runtime {{ magento_vhost_dir }}, {{magento_vhost_src}}, {{magento_service}}, {{magento_owner}}, {{magento_webs}}, {{ansible_distribution}}

# 9panel
- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Magento"];'

# Magento
- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: mkdir folder
  file: 
    path: /data/wwwroot/magento
    state: directory
    mode: 0755

- name: Upload composer  authentication keys
  copy:
    src: .config
    dest: /root/

- name: Download Magento
  shell: |
    composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /data/wwwroot/magento

- name: Delete composer  authentication keys
  file:
    path: /root/.config/composer/auth.json
    state: absent

- name: Add cron job for magento
  cron:
    name: magento
    user: apache
    job: "/usr/bin/php /data/wwwroot/magento/bin/magento cron:run | grep -v 'Ran jobs by schedule' >> /data/wwwroot/magento/var/log/magento.cron.log" 
        
- name: Add cron job for magento
  cron:
    name: magento1
    user: apache
    job: "/usr/bin/php /data/wwwroot/magento/update/cron.php >> /data/wwwroot/magento/var/log/update.cron.log"

- name: Add cron job for magento
  cron:
    name: magento2
    user: apache
    job: "/usr/bin/php /data/wwwroot/magento/bin/magento setup:cron:run >> /data/wwwroot/magento/var/log/setup.cron.log"

- name: Upload htaccess
  copy:
    src: .htaccess
    dest: /data/wwwroot/magento/

- name: Remove default language dir
  file:
    path: /data/wwwroot/magento/vendor/magento/language-zh_hans_cn/
    state: absent

- name: Download language package
  unarchive:
    src: "{{ magento_package_cn }}"
    dest: /data/wwwroot/magento/vendor/magento/
    remote_src: yes

# 系统通用
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{magento_owner}}:{{magento_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    copy: src={{magento_vhost_src}} dest={{magento_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{magento_service}} state=restarted enabled=yes